name: Contracts CI/CD
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache yarn modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Cache contracts
        uses: actions/cache@v3
        with:
          path: |
            packages/*/cache
            packages/*/artifacts
          key: contracts-${{ hashFiles('packages/*/contracts/**/*.sol') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run coverage
        run: yarn coverage

      - name: Upload report
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
